### ISSUE TITLE
It needs to be more convenient to build

### ISSUE THREAD

**Issue by rminnich** [bldy/build#50]
One thing I like about the old build tool is reasonable default behaviour: type
build /path/to
and if there is a build.json in there it runs it.

I'd like bldy to do this too.
bldy /path/to
will find a BUILD file in /path/to and run the :all target if it exists; if not it will error on either missing target or missing BUILD and even list the targets it found.

**Comment by sevki** [comment]
so this already exists, I think hank implemented this a while back according to bazel rules. You can look at his notes at #30 

the default behaviour is if you want to build something in a path it does these expansions,
`//sys/src/libc` becomes `//sys/src/libc:libc`
`//sys/src/9/amd64` becomes `//sys/src/9/amd64:amd64`
when there is not target name the package containing folder becomes the target name.

there is not default behaviour for 
`//.` so I don't know what will happen if you do that.

**Comment by sevki** [comment]
@rminnich can I close this?

**Comment by rminnich** [comment]
sure, I'll reopen if it doesn't work well for me :-)

**Comment by sevki** [comment]
cool.
